# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

import arro3.core

__all__ = [
    "CachedDataset",
    "CachedDatasetReader",
]

@typing.final
class CachedDataset:
    r"""
    A hybrid memory+disk cached Arrow dataset.

    Wraps an upstream Arrow stream source (any Python object implementing
    `__arrow_c_stream__`) and stores each `RecordBatch` in a Foyer hybrid
    cache keyed by a monotonic `u64` batch index.  Batches are ingested
    lazily: the upstream is only read when a reader requests a batch that has
    not been ingested yet.

    Multiple independent `CachedDatasetReader` handles can be obtained via
    `reader()`, each starting at a configurable position.

    Example::

        import pyarrow as pa
        from batchcorder import CachedDataset

        table = pa.table({"x": [1, 2, 3]})
        ds = CachedDataset(table, memory_capacity=64*1024*1024,
                          disk_path="/tmp/cache", disk_capacity=512*1024*1024)

        # Use directly as an Arrow stream:
        result = pa.RecordBatchReader.from_stream(ds).read_all()

        # Or get independent replay handles:
        r1 = ds.reader()
        r2 = ds.reader()
    """

    def __new__(
        cls,
        reader: typing.Any,
        memory_capacity: builtins.int,
        disk_path: builtins.str,
        disk_capacity: builtins.int,
    ) -> CachedDataset:
        r"""
        Create a new `CachedDataset`.

        Args:
            reader: Any Python object implementing ``__arrow_c_stream__``
                (e.g. a PyArrow table/reader, an arro3 RecordBatchReader, etc.)
            memory_capacity: In-memory cache tier size in bytes.
            disk_path: Directory in which Foyer stores the disk cache files.
            disk_capacity: Disk cache tier size in bytes.
        """
    @property
    def schema(self) -> arro3.core.Schema:
        r"""
        The Arrow schema of this dataset.
        """
    @property
    def ingested_count(self) -> builtins.int:
        r"""
        Number of batches ingested from the upstream so far.
        """
    @property
    def upstream_exhausted(self) -> builtins.bool:
        r"""
        `True` if the upstream reader has been fully consumed.
        """
    def reader(self, from_start: builtins.bool = ...) -> CachedDatasetReader:
        r"""
        Create a new `CachedDatasetReader` handle.

        Args:
            from_start: If ``True`` (default), the reader starts at batch
                index 0 and replays the full stream.  If ``False``, the
                reader starts at the current ingestion frontier.
        """
    def __iter__(self) -> CachedDatasetReader:
        r"""
        Iterate over this dataset's batches from the start.

        Creates a fresh reader at batch 0 and returns it as the iterator.
        """
    def ingest_all(self) -> builtins.int:
        r"""
        Eagerly ingest all remaining batches from the upstream reader into the cache.

        After this call, `upstream_exhausted` is `True` and the upstream object
        is released.  Subsequent readers will be served entirely from the cache.
        """
    def __arrow_c_stream__(self, requested_schema: typing.Any = None) -> typing.Any: ...
    def __arrow_c_schema__(self) -> typing.Any: ...

@typing.final
class CachedDatasetReader:
    r"""
    A single-use reader handle for a `CachedDataset`.

    Maintains an independent read position.  Multiple readers backed by the
    same dataset share the underlying cache; the upstream is ingested lazily as
    needed.

    The reader is consumed once exported via ``__arrow_c_stream__`` and is
    marked closed afterwards.
    """

    @property
    def schema(self) -> arro3.core.Schema:
        r"""
        The Arrow schema of this reader.
        """
    @property
    def closed(self) -> builtins.bool:
        r"""
        `True` if the underlying stream has been consumed.
        """
    def __iter__(self) -> CachedDatasetReader: ...
    def __next__(self) -> arro3.core.RecordBatch: ...
    def __arrow_c_stream__(self, requested_schema: typing.Any = None) -> typing.Any: ...
    def __arrow_c_schema__(self) -> typing.Any: ...
